#!/usr/bin/env python3
"""
HelloTalk API Client — Built from captured traffic data.

This client reads auth tokens from captures/auth_token.json
(generated by analyze-traffic.py) and makes API calls to understand
how the algorithm works.

Usage:
    python scripts/ht-client.py profile        — Get your profile
    python scripts/ht-client.py discovery       — Check discovery feed
    python scripts/ht-client.py moments         — Get your moments
    python scripts/ht-client.py visibility-test — Run a visibility diagnostic
"""

import json
import sys
import time
import random
from pathlib import Path

try:
    import httpx
except ImportError:
    print("Install httpx first: pip install httpx")
    sys.exit(1)


class HelloTalkClient:
    def __init__(self, config_path="captures/analyzed_endpoints.json",
                 auth_path="captures/auth_token.json"):
        self.config = self._load_json(config_path)
        self.auth = self._load_json(auth_path)

        if not self.auth:
            print("⚠ No auth token found. Run analyze-traffic.py first.")
            print("  See: python scripts/analyze-traffic.py --help")
            sys.exit(1)

        # Discover base URL from captured endpoints
        self.base_url = self._find_base_url()
        print(f"Base URL: {self.base_url}")

        self.client = httpx.Client(
            base_url=self.base_url,
            timeout=30,
            headers=self._build_headers(),
        )

    def _load_json(self, path):
        p = Path(path)
        if p.exists():
            with open(p) as f:
                return json.load(f)
        return {}

    def _find_base_url(self):
        """Extract base URL from captured traffic."""
        for key, data in self.config.items():
            url = data.get("example_url", "")
            if "hellotalk" in url:
                from urllib.parse import urlparse
                parsed = urlparse(url)
                return f"{parsed.scheme}://{parsed.netloc}"
        return "https://web.hellotalk.com"

    def _build_headers(self):
        """Build headers from captured auth data."""
        headers = {
            "Accept": "application/json",
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        }
        headers.update(self.auth)
        return headers

    def _delay(self):
        """Human-like delay between requests."""
        time.sleep(random.uniform(1.5, 4.0))

    def _request(self, method, path, **kwargs):
        """Make a request with logging and delay."""
        self._delay()
        try:
            resp = self.client.request(method, path, **kwargs)
            print(f"\n{'─'*50}")
            print(f"{method} {path} → {resp.status_code}")

            # Log rate limit headers
            for h, v in resp.headers.items():
                if "rate" in h.lower() or "limit" in h.lower() or "retry" in h.lower():
                    print(f"  ⚠ {h}: {v}")

            try:
                body = resp.json()
                print(f"  Response preview:")
                preview = json.dumps(body, indent=2, ensure_ascii=False)
                if len(preview) > 1000:
                    print(preview[:1000] + "\n  ... (truncated)")
                else:
                    print(preview)
                return body
            except Exception:
                print(f"  Response: <{len(resp.content)} bytes, non-JSON>")
                return resp.text
        except Exception as e:
            print(f"  ERROR: {e}")
            return None

    def get(self, path, **kwargs):
        return self._request("GET", path, **kwargs)

    def post(self, path, **kwargs):
        return self._request("POST", path, **kwargs)

    # === HIGH-LEVEL COMMANDS ===

    def cmd_profile(self):
        """Fetch your own profile to verify auth works."""
        print("\n=== Fetching your profile ===")
        # Try common endpoint patterns
        for path in ["/api/v1/ht/users/me", "/user/profile", "/api/user/me", "/me"]:
            if self._find_endpoint("user", "profile", "me"):
                break
        # Use whatever endpoint we find that contains 'user' or 'profile'
        endpoint = self._find_endpoint("user", "profile", "me")
        if endpoint:
            return self.get(endpoint)
        print("  Profile endpoint not found in captured traffic.")
        print("  Browse your profile on web.hellotalk.com while capturing.")
        return None

    def cmd_discovery(self):
        """Check the discovery feed to see what the API returns."""
        print("\n=== Checking discovery feed ===")
        endpoint = self._find_endpoint("discover", "search", "find", "partner", "recommend")
        if endpoint:
            return self.get(endpoint)
        print("  Discovery endpoint not found in captured traffic.")
        print("  Browse the 'Find Partners' tab on web.hellotalk.com while capturing.")
        return None

    def cmd_moments(self):
        """Fetch moments feed."""
        print("\n=== Fetching moments ===")
        endpoint = self._find_endpoint("moment", "feed", "timeline")
        if endpoint:
            return self.get(endpoint)
        print("  Moments endpoint not found.")
        print("  Browse Moments on web.hellotalk.com while capturing.")
        return None

    def cmd_visibility_test(self):
        """Run a diagnostic to assess account visibility."""
        print("\n=== Running Visibility Diagnostic ===\n")

        results = {}

        # 1. Profile check
        print("1. Checking profile...")
        profile = self.cmd_profile()
        if profile:
            results["profile"] = profile
            print("  ✓ Profile accessible")
        else:
            print("  ✗ Could not fetch profile")

        # 2. Discovery check
        print("\n2. Checking discovery placement...")
        discovery = self.cmd_discovery()
        if discovery:
            results["discovery"] = discovery
            if isinstance(discovery, dict):
                users = discovery.get("data", discovery.get("users", discovery.get("results", [])))
                if isinstance(users, list):
                    print(f"  Discovery returned {len(users)} users")
        else:
            print("  ✗ Could not fetch discovery")

        # 3. Moments check
        print("\n3. Checking moments feed...")
        moments = self.cmd_moments()
        if moments:
            results["moments"] = moments
            print("  ✓ Moments accessible")
        else:
            print("  ✗ Could not fetch moments")

        # Save results
        output = Path("captures") / "visibility_diagnostic.json"
        with open(output, "w") as f:
            json.dump(results, f, indent=2, default=str, ensure_ascii=False)
        print(f"\n  Full diagnostic saved to: {output}")

        return results

    def _find_endpoint(self, *keywords):
        """Find a captured endpoint matching any keyword."""
        for key in self.config:
            path = key.split(" ", 1)[-1] if " " in key else key
            if any(kw in path.lower() for kw in keywords):
                return path
        return None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    cmd = sys.argv[1].lower().replace("-", "_")
    client = HelloTalkClient()

    commands = {
        "profile": client.cmd_profile,
        "discovery": client.cmd_discovery,
        "moments": client.cmd_moments,
        "visibility_test": client.cmd_visibility_test,
    }

    if cmd in commands:
        commands[cmd]()
    else:
        print(f"Unknown command: {cmd}")
        print(f"Available: {', '.join(commands.keys())}")


if __name__ == "__main__":
    main()
